### ISSUE TITLE
There is an issue with the StackStorm Kafka pack in stackstorm 3.8.0

### ISSUE THREAD

**Issue by Bindu-yadav8** [StackStorm-Exchange/stackstorm-kafka#18]
It seems that the Kafka pack is not compatible with st2 3.8.0, on Python 3.8.10. I am currently experiencing an issue with the StackStorm Kafka pack, and I'm reaching out to the community for assistance.

Seeing invalid syntax error (uses a newly reserved keyword: async)

> 'st2 run kafka.produce topic=test message='StackStorm meets Apache Kafka'

> 'stderr: "Traceback (most recent call last):
> File "/opt/stackstorm/st2/lib/python3.8/site-packages/python_runner/python_action_wrapper.py", line 264, in _get_action_instance
> actions_cls = action_loader.register_plugin(Action, self._file_path)
> File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/util/loader.py", line 173, in register_plugin
> module = imp.load_source(module_name, plugin_abs_file_path)
> File "/usr/lib/python3.8/imp.py", line 171, in load_source
> module = _load(spec)
> File "", line 702, in _load
> File "", line 671, in _load_unlocked
> File "", line 848, in exec_module
> File "", line 219, in _call_with_frames_removed
> File "/opt/stackstorm/packs/kafka/actions/produce.py", line 2, in
> from kafka import SimpleProducer, KafkaClient
> File "/opt/stackstorm/virtualenvs/kafka/lib/python3.8/site-packages/kafka/init.py", line 12, in
> from kafka.producer import SimpleProducer, KeyedProducer
> File "/opt/stackstorm/virtualenvs/kafka/lib/python3.8/site-packages/kafka/producer/init.py", line 1, in
> from .simple import SimpleProducer
> File "/opt/stackstorm/virtualenvs/kafka/lib/python3.8/site-packages/kafka/producer/simple.py", line 58
> return '' % self.async
> ^
> SyntaxError: invalid syntax`

If anyone has experience with this issue or suggestions for troubleshooting, I would greatly appreciate your insights.

Thank you in advance for your time and assistance.

@armab

**Comment by Bindu-yadav8** [comment]
@alexandrejuma I see that you had posted the same issue with respect to Stackstorm-kafka integration pack. Did that get resolved?

**Comment by Bindu-yadav8** [comment]
@armab Any update on this issue, I still see kafka plugin is incompatible. 

`root@CNAS-STACKSTORM-DEV-1:/opt/stackstorm/configs# st2 run kafka.produce topic=test message='StackStorm meets Apache Kafka'
.
id: 6548848bad69bb37a2e19956
action.ref: kafka.produce
context.user: st2admin
parameters:
  message: StackStorm meets Apache Kafka
  topic: test
status: failed
start_timestamp: Mon, 06 Nov 2023 06:15:39 UTC
end_timestamp: Mon, 06 Nov 2023 06:15:39 UTC
result:
  exit_code: 1
  result: None
  stderr: "Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/python_runner/python_action_wrapper.py", line 264, in _get_action_instance
    actions_cls = action_loader.register_plugin(Action, self._file_path)
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/util/loader.py", line 173, in register_plugin
    module = imp.load_source(module_name, plugin_abs_file_path)
  File "/usr/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/stackstorm/packs/kafka/actions/produce.py", line 2, in <module>
    from kafka import SimpleProducer, KafkaClient
  File "/opt/stackstorm/virtualenvs/kafka/lib/python3.8/site-packages/kafka/__init__.py", line 12, in <module>
    from kafka.producer import SimpleProducer, KeyedProducer
  File "/opt/stackstorm/virtualenvs/kafka/lib/python3.8/site-packages/kafka/producer/__init__.py", line 1, in <module>
    from .simple import SimpleProducer
  File "/opt/stackstorm/virtualenvs/kafka/lib/python3.8/site-packages/kafka/producer/simple.py", line 58
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/python_runner/python_action_wrapper.py", line 395, in <module>
    obj.run()
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/python_runner/python_action_wrapper.py", line 213, in run
    action = self._get_action_instance()
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/python_runner/python_action_wrapper.py", line 274, in _get_action_instance
    raise exc_cls(msg)
SyntaxError: Failed to load action class from file "/opt/stackstorm/packs/kafka/actions/produce.py" (action file most likely doesn't exist or contains invalid syntax): invalid syntax (simple.py, line 58)

Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/python_runner/python_action_wrapper.py", line 264, in _get_action_instance
    actions_cls = action_loader.register_plugin(Action, self._file_path)
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/util/loader.py", line 173, in register_plugin
    module = imp.load_source(module_name, plugin_abs_file_path)
  File "/usr/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/stackstorm/packs/kafka/actions/produce.py", line 2, in <module>
    from kafka import SimpleProducer, KafkaClient
  File "/opt/stackstorm/virtualenvs/kafka/lib/python3.8/site-packages/kafka/__init__.py", line 12, in <module>
    from kafka.producer import SimpleProducer, KeyedProducer
  File "/opt/stackstorm/virtualenvs/kafka/lib/python3.8/site-packages/kafka/producer/__init__.py", line 1, in <module>
    from .simple import SimpleProducer
  File "/opt/stackstorm/virtualenvs/kafka/lib/python3.8/site-packages/kafka/producer/simple.py", line 58
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax

"
  stdout: ''
`

**Comment by armab** [comment]
@Bindu-yadav8 I'm not using Kafka pack so can't assist here.

If this pack seems to be important in your day-to-day operations, - consider investing in development and contributing a fix. We'll be happy to review and accept it.
There are around 150 stackstorm packs in the Exchange. StackStorm is as good as the community of users are contributing back and keeping the different parts of the system in a working state.

**Comment by alexandrejuma** [comment]
> @alexandrejuma I see that you had posted the same issue with respect to Stackstorm-kafka integration pack. Did that get resolved?

Honestly, it was so many years ago. I have no idea.

But just checked the PRs and there's one with the objective of getting the pack working with Python 3.8 (the original issue I reported).

https://github.com/StackStorm-Exchange/stackstorm-kafka/pull/16/commits

It has failed some automated build/test at the time and logs are no longer available. Maybe you can pick it up from there and finish the job with your contribution.

**Comment by Bindu-yadav8** [comment]
@acc-rajbarath-govindan
