### ISSUE TITLE
Workflows not getting triggered when new message arrives to the Kafka Topic

### ISSUE THREAD

**Issue by Bindu-yadav8** [StackStorm-Exchange/stackstorm-kafka#20]
Hello Community,

I recently installed the new version of Kafka Integration pack in my system. Updated the config file as below:

> client_id: st2-kafka-producer
> hosts: 172.1.0.0:9092
> gcp_message_sensor:
>   hosts: 172.1.0.0:9092
>   topics: ['Predicted-Node-Failure', 'Zabbix-Normalized-Alert']
>   group_id: st2gcpgroup
>   clienit_id: st2gcpclient
> message_sensor:
>   hosts: 172.1.0.0:9092
>   topics: ['Predicted-Node-Failure', 'Zabbix-Normalized-Alert']
>   group_id: test-consumer-group  //this is the consumer group ID from other server where Kafka is installed
>   client_id: st2-kafka-consumer
> 

I have set the Rules in Stackstorm web UI this way, so that any new messages that arrives to Kafka topic, the following action should get triggered.

<img width="634" alt="image" src="https://github.com/StackStorm-Exchange/stackstorm-kafka/assets/86333293/aafab60b-f365-4080-805f-252b068af459">

<img width="635" alt="image" src="https://github.com/StackStorm-Exchange/stackstorm-kafka/assets/86333293/0c4aa1a4-0573-4f99-aae8-308aa3240627">

<img width="635" alt="image" src="https://github.com/StackStorm-Exchange/stackstorm-kafka/assets/86333293/49cc9f13-6e5d-4823-a08a-44dabf40fe49">

When I try to publish some sample messages to the above Kafka topic in other server to test whether the rule is getting triggered, I see there is no executions happening and when I see the logs /var/log/st2/st2sensorcontainer.log

`root@CNAS-STACKSTORM-DEV-1:/var/log/st2# tail -1000f st2sensorcontainer.log

2024-01-19 05:23:53,055 140698618144016 ERROR (unknown file) [-]
2024-01-19 05:23:53,056 140698618144016 ERROR (unknown file) [-] self._sensor_instance.cleanup()
2024-01-19 05:23:53,056 140698618144016 ERROR (unknown file) [-]

2024-01-19 05:23:53,056 140698618144016 ERROR (unknown file) [-]   File "/opt/stackstorm/packs/kafka/sensors/gcp_message_sensor.py", line 105, in cleanup

2024-01-19 05:23:53,057 140698618144016 ERROR (unknown file) [-]
2024-01-19 05:23:53,057 140698618144016 ERROR (unknown file) [-] self._consumer._client.close()
2024-01-19 05:23:53,057 140698618144016 ERROR (unknown file) [-]

2024-01-19 05:23:53,057 140698618144016 ERROR (unknown file) [-] AttributeError
2024-01-19 05:23:53,057 140698618144016 ERROR (unknown file) [-] :
2024-01-19 05:23:53,057 140698618144016 ERROR (unknown file) [-] 'NoneType' object has no attribute '_client'
2024-01-19 05:23:53,057 140698618144016 ERROR (unknown file) [-]

2024-01-19 05:23:56,991 140169854921536 INFO process_container [-] Process for sensor kafka.KafkaGCPMessageSensor has exited with code 1
2024-01-19 05:23:56,993 140169854921536 INFO process_container [-] Process for sensor kafka.KafkaMessageSensor has exited with code 1
2024-01-19 06:27:01,289 140169854919952 INFO manager [-] Sensor kafka.KafkaGCPMessageSensor updated. Reloading sensor.
2024-01-19 06:27:01,290 140169854919952 WARNING process_container [-] Sensor kafka.KafkaGCPMessageSensor isn't running in this container.
2024-01-19 06:27:01,309 140169854919952 WARNING api [-] "auth.api_url" configuration option is not configured
2024-01-19 06:27:01,337 140169854919952 INFO manager [-] Sensor kafka.KafkaGCPMessageSensor reloaded.
2024-01-19 06:27:01,338 140169854919952 INFO manager [-] Sensor kafka.KafkaMessageSensor updated. Reloading sensor.
2024-01-19 06:27:01,339 140169854919952 WARNING process_container [-] Sensor kafka.KafkaMessageSensor isn't running in this container.
2024-01-19 06:27:01,344 140169854919952 WARNING api [-] "auth.api_url" configuration option is not configured
2024-01-19 06:27:01,368 140169854919952 INFO manager [-] Sensor kafka.KafkaMessageSensor reloaded.
2024-01-19 06:27:02,295 139771929179408 INFO sensor_wrapper [-] No config found for sensor "FileWatchSensor"
2024-01-19 06:27:02,296 139771929179408 INFO sensor_wrapper [-] Watcher started
2024-01-19 06:27:02,296 139771929179408 INFO sensor_wrapper [-] Running sensor initialization code
2024-01-19 06:27:02,330 139771929179408 INFO sensor_wrapper [-] Running sensor in passive mode
2024-01-19 06:27:02,337 139771876186240 INFO mixins [-] Connected to amqp://guest:**@127.0.0.1:5672//
2024-01-19 06:27:02,490 140582010803472 INFO sensor_wrapper [-] Found config for sensor "KafkaMessageSensor"
2024-01-19 06:27:02,491 140582010803472 INFO sensor_wrapper [-] Watcher started
2024-01-19 06:27:02,491 140582010803472 INFO sensor_wrapper [-] Running sensor initialization code
2024-01-19 06:27:02,491 140582010803472 ERROR (unknown file) [-] Traceback (most recent call last):
2024-01-19 06:27:02,492 140582010803472 ERROR (unknown file) [-]   File "/opt/stackstorm/packs/kafka/sensors/message_sensor.py", line 47, in setup

2024-01-19 06:27:02,492 140582010803472 ERROR (unknown file) [-]
2024-01-19 06:27:02,493 140582010803472 ERROR (unknown file) [-] self._consumer = KafkaConsumer(*self._topics,
2024-01-19 06:27:02,493 140582010803472 ERROR (unknown file) [-]

2024-01-19 06:27:02,493 140582010803472 ERROR (unknown file) [-]   File "/opt/stackstorm/virtualenvs/kafka/lib/python3.8/site-packages/kafka/consumer/group.py", line 316, in __init__

2024-01-19 06:27:02,493 140582010803472 ERROR (unknown file) [-]
2024-01-19 06:27:02,493 140582010803472 ERROR (unknown file) [-] raise KafkaConfigurationError("Unrecognized configs: %s" % (extra_configs,))
2024-01-19 06:27:02,493 140582010803472 ERROR (unknown file) [-]

2024-01-19 06:27:02,493 140582010803472 ERROR (unknown file) [-] kafka.errors
2024-01-19 06:27:02,493 140582010803472 ERROR (unknown file) [-] .
2024-01-19 06:27:02,493 140582010803472 ERROR (unknown file) [-] KafkaConfigurationError
2024-01-19 06:27:02,493 140582010803472 ERROR (unknown file) [-] :
2024-01-19 06:27:02,493 140582010803472 ERROR (unknown file) [-] KafkaConfigurationError: Unrecognized configs: {'deserializer_class'}
2024-01-19 06:27:02,494 140582010803472 ERROR (unknown file) [-]

2024-01-19 06:27:02,494 140582010803472 INFO sensor_wrapper [-] Stopping trigger watcher
2024-01-19 06:27:02,495 140582010803472 INFO sensor_wrapper [-] Invoking cleanup on sensor
2024-01-19 06:27:02,495 140582010803472 ERROR (unknown file) [-] Error in atexit._run_exitfuncs:

2024-01-19 06:27:02,495 140582010803472 ERROR (unknown file) [-] Traceback (most recent call last):

2024-01-19 06:27:02,495 140582010803472 ERROR (unknown file) [-]   File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2reactor/container/sensor_wrapper.py", line 302, in stop

2024-01-19 06:27:02,495 140582010803472 ERROR (unknown file) [-]
2024-01-19 06:27:02,496 140582010803472 ERROR (unknown file) [-] self._sensor_instance.cleanup()
2024-01-19 06:27:02,496 140582010803472 ERROR (unknown file) [-]

2024-01-19 06:27:02,496 140582010803472 ERROR (unknown file) [-]   File "/opt/stackstorm/packs/kafka/sensors/message_sensor.py", line 101, in cleanup

2024-01-19 06:27:02,496 140582010803472 ERROR (unknown file) [-]
2024-01-19 06:27:02,496 140582010803472 ERROR (unknown file) [-] self._consumer._client.close()
2024-01-19 06:27:02,496 140582010803472 ERROR (unknown file) [-]

2024-01-19 06:27:02,496 140582010803472 ERROR (unknown file) [-] AttributeError
2024-01-19 06:27:02,496 140582010803472 ERROR (unknown file) [-] :
2024-01-19 06:27:02,496 140582010803472 ERROR (unknown file) [-] 'NoneType' object has no attribute '_client'
2024-01-19 06:27:02,497 140582010803472 ERROR (unknown file) [-]

`

Can someone help here to understand the issue or any suggestions?  
Thanks in advance!

@arm4b @cognifloyd

**Comment by Bindu-yadav8** [comment]
Looping @acc-rajbarath-govindan
